color: lime
fieldLayouts:
  a534c366-829c-4d99-8265-64b389de5151:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: b26cb647-0725-41e4-abbb-3e5660a664e9
        userCondition: null
handle: aboutMe
hasTitleField: false
icon: address-book
name: 'About me'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
