color: yellow
fieldLayouts:
  ac6c8345-08da-457e-b1cb-1040fe652514:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 6f9f5e9d-3102-4054-916e-21a175c2e615
        userCondition: null
handle: contact
hasTitleField: false
icon: phone
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
