color: null
fieldLayouts:
  f0a18aa1-850f-44c2-b96c-e8fb17d5dc06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-10T18:44:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e267d81d-53e6-472b-a465-895c5fb07506
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T18:50:59+00:00'
            elementCondition: null
            fieldUid: 643e2a1b-c91c-4e6a-9202-c9d35696ec1b # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3051ff9-a998-4b0b-a692-9a0bb32aea87
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T18:50:59+00:00'
            elementCondition: null
            fieldUid: 5cbbc156-a371-4496-b3ac-59ef92544ad4 # Content ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f97df412-c1d5-4aaf-9c32-d989d420ab82
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T20:44:38+00:00'
            elementCondition: null
            fieldUid: c533096a-5a5d-4e70-a0bc-98116828e93c # Link address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce282af0-4d30-4dc2-b90b-d284009dba51
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T20:44:38+00:00'
            elementCondition: null
            fieldUid: 8bfc608a-38b7-45e6-9ddb-eb93390c8509 # Related entries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50678460-b0f3-4a4b-9178-b0914fb49d43
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 46d66d44-a716-4239-8e3b-1ed5ebc4aede
        userCondition: null
handle: menuOption
hasTitleField: true
icon: ballot-check
name: 'Menu option'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
