color: fuchsia
fieldLayouts:
  146ea08c-eddc-4076-9724-8722566b4172:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: a7e6084b-9f47-406b-b400-dc9b1db348e2
        userCondition: null
handle: pastWorkCollection
hasTitleField: false
icon: computer-classic
name: 'Past Work Collection'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
