color: orange
fieldLayouts:
  b27a7b9f-49a9-4b87-b3b5-cdecc36c2042:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 73c7c029-89f2-4f91-99df-2c7652f54f06
        userCondition: null
handle: socialMediaCollection
hasTitleField: false
icon: album-collection
name: 'Social Media Collection'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
