columnSuffix: null
handle: backgroundColor
instructions: null
name: 'Background color'
searchable: false
settings:
  defaultColor: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
