columnSuffix: null
handle: body
instructions: null
name: Body
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 9641bf8b-4fe2-4b5a-8db9-bf1c4f9dd9b1 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
