columnSuffix: null
handle: canBeDuplicated
instructions: null
name: 'Can be duplicated?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
