columnSuffix: null
handle: contactInformation
instructions: null
name: 'Contact information'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Name
            -
              - handle
              - name
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Link
            -
              - handle
              - link
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Quick response?'
            -
              - handle
              - quickResponse
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - Type
            -
              - handle
              - type
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - Web
                    -
                      - value
                      - web
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - Email
                    -
                      - value
                      - email
                    -
                      - default
                      - false
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - web
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: language
type: craft\fields\Table
