dateModified: 1734212775
email:
  fromEmail: tom.faust@hotmail.com
  fromName: portfolio-craft
  transportType: craft\mail\transportadapters\Sendmail
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
meta:
  __names__:
    0e2c6c12-f0c0-40d0-a364-c123f2425a77: 'Contact list' # Contact list
    01a69c9a-b952-4a89-9b5c-24ad86df8558: 'Menu option' # Menu option
    1ef4c050-d814-47c6-9dbb-2449c83d9fa7: Files # Files
    3afe07f1-ed58-464e-b819-32f74b4d7dd2: Welcome # Welcome
    5cbbc156-a371-4496-b3ac-59ef92544ad4: 'Content ID' # Content ID
    5d1b3eb3-1f31-4d23-a940-147a23d28e8c: 'Past work' # Past work
    5dbfae60-be3c-4927-8d3a-f96448c7d460: 'portfolio-craft EN' # portfolio-craft EN
    6a3d40f8-2fc0-4970-83ff-d661ac632f5a: portfolio-craft # portfolio-craft
    6e769d75-e442-4b05-ba57-e73cb899fa01: 'Background color' # Background color
    7f79c45d-f61f-468d-ba54-dbb8d1392a1b: 'Past work' # Past work
    8bfc608a-38b7-45e6-9ddb-eb93390c8509: 'Related entries' # Related entries
    9bea43b7-4dc0-4b23-aaff-de1542ed1d25: Cursors # Cursors
    11f7aaad-caf4-471a-97c9-9b70a976f8ac: CV # CV
    017bb80c-d54d-429b-ab44-a3f221b8a4e9: Welcome # Welcome
    18cdd73c-6b27-4d28-8dfc-40bd682e5fb3: 'Social media' # Social media
    42c395fa-2f2c-472c-a879-7dc4a5a674b4: 'Public Schema' # Public Schema
    42cf421d-1754-4f06-a1fa-3e8d331345c5: 'About me topics' # About me topics
    44bff4d4-3cea-4c2d-8f3c-5d95fb9625a5: 'Welcome Buttons' # Welcome Buttons
    74ad5976-0667-425c-9d28-9da4e19ee4b2: Menu # Menu
    083c96d3-40a7-4356-b658-72ab101009fb: 'About me entries' # About me entries
    91df1c71-2eec-4714-9dbf-8bca03578466: Icon # Icon
    357a9117-f4c9-48f2-a5d4-d379e8bc0106: Display # Display
    425b468c-09d1-4045-9c3f-4fb36de779b1: 'Background image' # Background image
    588c86b3-d417-4ffe-819a-5cd9d3a9e96f: Contact # Contact
    643e2a1b-c91c-4e6a-9202-c9d35696ec1b: Icon # Icon
    686f9f04-92ac-4891-aed9-17766b5ca11c: 'Window Type' # Window Type
    803ba08e-ff62-46da-ac27-690cde4e4307: Cursor # Cursor
    941efea7-0adc-4d0b-bc23-0852610418fe: Icons # Icons
    9641bf8b-4fe2-4b5a-8db9-bf1c4f9dd9b1: Simple # Simple
    51878c60-71bc-44b1-adc0-5ef67acf0686: Normal # Normal
    a9f99a5f-a049-46a8-bd54-4d21598bee37: 'Window icon' # Window icon
    a89477f6-db77-4efe-ada2-dcb6bf2b1196: Pointer # Pointer
    ab6e59b5-86aa-43e3-b11c-d4caf58c260c: CV # CV
    b2ffb493-b152-4dc2-b7d4-ef22f7c27bc5: Image # Image
    c533096a-5a5d-4e70-a0bc-98116828e93c: 'Link address' # Link address
    cb332bee-298c-486d-b275-957dbfd14f7f: 'About me' # About me
    d4bc21ab-1729-4dcf-a03c-bae1b33ce69a: Body # Body
    da878ded-8b92-4d04-bf6e-78fe822b5b8e: 'Can be duplicated?' # Can be duplicated?
    dfe1a1a4-9868-486f-bb56-0b187a82fde1: 'Pdf file' # Pdf file
    ecbaba17-c1a7-4e70-8a37-06a312e4de04: portfolio-craft # portfolio-craft
    efee04a0-8339-4651-b2f8-cb41af9e4c23: Topic # Topic
    f0582ffa-fa9f-4cfe-a72d-3d26eba3a594: 'Social media' # Social media
    fc18808b-0848-403e-9b71-3493b62b47c0: 'Contact information' # Contact information
plugins:
  _portfolio-core:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  portfolio-core:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: portfolio-craft
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
