defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7f79c45d-f61f-468d-ba54-dbb8d1392a1b # Past work
handle: pastWork
maxAuthors: 1
name: 'Past work'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5dbfae60-be3c-4927-8d3a-f96448c7d460: # portfolio-craft EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  6a3d40f8-2fc0-4970-83ff-d661ac632f5a: # portfolio-craft
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: a8c66cfe-0992-4878-ad66-732821b26358
type: structure
