defaultPlacement: end
enableVersioning: true
entryTypes:
  - f0582ffa-fa9f-4cfe-a72d-3d26eba3a594 # Social media
handle: socialMedia
maxAuthors: 1
name: 'Social media'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5dbfae60-be3c-4927-8d3a-f96448c7d460: # portfolio-craft EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  6a3d40f8-2fc0-4970-83ff-d661ac632f5a: # portfolio-craft
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
